name: GunGame
version: '1.0.2'
main: com.m3z0id.gunGame.GunGame
api-version: '1.21.4'
authors: [ M3z0id ]

dependencies:
  server:
    Vault:
      load: AFTER
      required: true
      join-classpath: true
    Essentials:
      load: AFTER
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: AFTER
      required: false
      join-classpath: true

permissions:
  gungame.admin:
    default: op