name: GunGame
version: '1.0'
main: com.m3z0id.gunGame.GunGame
api-version: '1.17'
authors: [ M3z0id ]
depend: [Vault, Essentials, PlacehodlerAPI]

commands:
  gungame:
    usage: /<command> [reset]/[stats] <player> [set/add] <number> [kills/deaths/levels]
    permission: gungame.admin

permissions:
  gungame.admin:
    default: op